import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const intranet = localFont({
  src: [{
    path: './fonts/intranet.otf',
  }
  ]
})

export const intranet_outline = localFont({
  src: [
    {
      path: "./fonts/intranet_outline.otf",
    },
  ],
});

const shinkaFont = localFont({
  src: "./fonts/shinkamono_thin.woff",
});

export const shinkaBoldFont = localFont({
  src: "./fonts/shinkamono_heavy.ttf",
});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={shinkaFont.className}>
        <body>
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
